### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by not7cd** [hs3city/whois#3]

**Comment by not7cd** [comment]
```
sudo docker run --expose=5000 0e23504dab14
INFO:werkzeug: * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
INFO:whois.web:connecting to db
[2018-03-31 01:00:11,362] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2457, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2691, in _connect
    **self.connect_params)
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1610, in full_dispatch_request
    rv = self.preprocess_request()
  File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1831, in preprocess_request
    rv = func()
  File "/whois/web.py", line 41, in before_request
    db.connect()
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2458, in connect
    self._initialize_connection(self._state.conn)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2310, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 171, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2457, in connect
    self._state.set_connection(self._connect())
  File "/usr/local/lib/python3.6/site-packages/peewee.py", line 2691, in _connect
    **self.connect_params)
peewee.OperationalError: unable to open database file
[2018-03-31 01:00:11,366] ERROR in web: unable to open database file
INFO:werkzeug:172.17.0.1 - - [31/Mar/2018 01:00:11] "GET / HTTP/1.1" 500 -
```
